### ISSUE TITLE
JBuilder 2.11.3: "NoMethodError Exception: undefined method `empty?` for PG::Result"

### ISSUE THREAD

**Issue by jtannas** [rails/jbuilder#516]
When rendering records returned by SQL JBuilder fails with 
```
NoMethodError Exception: undefined method `empty?` for PG::Result
```

Simplified example:
```ruby
irb(main):001:0> query_result = ActiveRecord::Base.connection.execute('SELECT * FROM users LIMIT 1')
=> #<PG::Result:0x00005594547c1120 status=PGRES_TUPLES_OK ntuples=1 nfields=31 cmd_tuples=1>
irb(main):002:0> query_result.empty?
(irb):2:in `<main>': undefined method `empty?' for #<PG::Result:0x00005594547c1120 status=PGRES_TUPLES_OK ntuples=1 nfields=31 cmd_tuples=1> (NoMethodError)
```

---
Ruby Version: 3.0.2p107
Jbuilder Gem Version: 2.11.3
PG Gem Version: 1.2.3

**Comment by dhh** [comment]
cc @yuki24

**Comment by yuki24** [comment]
https://github.com/rails/jbuilder/pull/524 should address this issue.

**Comment by yuki24** [comment]
Unfortunately this is a little incompatibility Introduced by #501. I have removed the `#empty?` call, but ActionView's `CollectionRenderer` requires [`#length` or `#size` to be implemented](https://github.com/rails/rails/blob/720e2da2bc1a0325bab98866a00733851db07a98/actionview/lib/action_view/renderer/collection_renderer.rb#L47-L53) in Rails 6.1.

@jtannas @dhh I wonder if this is okay...

**Comment by dhh** [comment]
Not sure I fully understand the issue? The enumerable passed in much implement #length or #size?

**Comment by jtannas** [comment]
> Unfortunately this is a little incompatibility Introduced by #501. I have removed the `#empty?` call, but ActionView's `CollectionRenderer` requires [`#length` or `#size` to be implemented](https://github.com/rails/rails/blob/720e2da2bc1a0325bab98866a00733851db07a98/actionview/lib/action_view/renderer/collection_renderer.rb#L47-L53) in Rails 6.1.

yeah, I'm seeing that in the test run when upgrading to 2.11.4 that it's still failing when attempting to render a PG::Result. 

```
     Failure/Error:
       json.partial!(
         'sample_partial',
         collection: @sample_pg_result,
         as: :row,
       )

     ActionView::Template::Error:
       undefined method `size' for #<PG::Result:0x0000563f594901a8 status=PGRES_TUPLES_OK ntuples=0 nfields=7 cmd_tuples=0>
       Did you mean?  fsize
 ```

**Comment by yuki24** [comment]
@jtannas Apologies for the long delay, but here is a fix for the broken compatibility: https://github.com/rails/jbuilder/pull/531
